---
# tasks file for master-setup
- name: "Installing k3s master"
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server' sh -s - --node-name {{ inventory_hostname }} --token {{ k3s_token }} --bind-address {{ hostvars['master'].ansible_host }} --cluster-init"
  register: k3s_install
  changed_when: k3s_install.rc != 0