- name: "Cluster prereq"
  hosts: k3s_cluster
  become: true
  roles:
    - role: k3s-prereq
- name: "Master setup"
  hosts: masters
  become: true
  vars:
    k3s_token: "KiratechDevOpsChallenge"
  roles:
    - role: master-setup
- name: "Workers setup"
  hosts: workers
  become: true
  vars:
    k3s_token: "KiratechDevOpsChallenge"
  roles:
    - role: worker-setup