---
# tasks file for worker-setup
- name: "Installing k3s worker"
  become: true
  vars:
    master_address : "https://" + {{ hostvars['master'].ansible_host }}
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='agent' sh -s - --token {{ k3s_token }} --server {{ master_address }}"
  register: k3s_install
  changed_when: k3s_install.rc != 0