---
# tasks file for worker-setup
- name: "Installing k3s worker"
  vars:
    master_address : "https://{{ hostvars['master'].ansible_host }}:6443"
  ansible.builtin.shell: |
                          curl -sfL https://get.k3s.io | \
                          sh -s - agent \
                          --write-kubeconfig-mode 644 \
                          --node-name {{ inventory_hostname }} \
                          --token {{ k3s_token }} \
                          --server {{ master_address }}
  register: k3s_install
  changed_when: k3s_install.rc != 0