#!/bin/bash
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y python3, python3-pip, git
sudo adduser ansible --disabled-password
sudo echo "ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
sudo mkdir /home/ansible/.ssh
sudo chmod 700 /home/ansible/.ssh
sudo touch /home/ansible/.ssh/authorized_keys
sudo cat /home/ubuntu/.ssh/authorized_keys > /home/ansible/.ssh/authorized_keys
sudo mv /home/ubuntu/.ssh/id_rsa /home/ansible/.ssh/id_rsa
sudo mv /home/ubuntu/.ssh/id_rsa.pub /home/ansible/.ssh/id_rsa.pub
sudo chmod 600 /home/ansible/.ssh/authorized_keys /home/ansible/.ssh/id_rsa /home/ansible/.ssh/id_rsa.pub
sudo chown -R ansible:ansible /home/ansible
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible -y