#!/bin/bash
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y python3, python3-pip, git
sudo adduser ansible --disabled-password
sudo usermod -aG sudo ansible
sudo mkdir /home/ansible/.ssh
sudo chmod 700 /home/ansible/.ssh
sudo touch /home/ansible/.ssh/authorized_keys
sudo chmod 600 /home/ansible/.ssh/authorized_keys
sudo cat /home/ubuntu/.ssh/authorized_keys > /home/ansible/.ssh/authorized_keys
sudo chown -R ansible:ansible /home/ansible