plugin: amazon.aws.aws_ec2
aws_region: eu-central-1
hostnames:
  - tag:Name
  - private-ip-address
keyed_groups:
  - key: tags.Type
    separator: ''

groups:
  k3s-cluster: "'DevOps Challenge' in tags.Project"

compose:
  ansible_user: ansible
  ansible_host: private_ip_address