plugin: amazon.aws.aws_ec2
aws_region: eu-central-1
hostnames:
  - tag:Name
  - private-ip-address
keyed_groups:
  - key: tags.Group
    separator: ''

groups:
  k3s-cluster: "'DevOps Challenge' in tags.Project"

compose:
  ansible_user: ansible
  ansible_host: private_ip_address
  ansible_port: 22
  k3s_version: v1.26.9+k3s1
  token: "KiratechChallenge"  # Use ansible vault if you want to keep it secret
  api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
  extra_server_args: ""
  extra_agent_args: ""
